### ISSUE TITLE
Search index error on build

### ISSUE THREAD

**Issue by judsonlmoore** [laughing-waffles/bikefi#4]
@edireson can you have a look at this error? 
https://github.com/laughing-waffles/financing.bike/runs/5357671624?check_suite_focus=true#step:8:9

**Comment by edireson** [comment]
Bundle should already be installed, so it feels like that script is duplicative? 

https://github.com/dieghernan/algolia-jekyll-action/blob/main/action.yml

So I pulled out just the bundle exec and tried to just run that: 
https://github.com/laughing-waffles/financing.bike/blob/9db2cd6b5e248d429607272b05177a314a245065/.github/workflows/jekyll.yaml#L26-28

We'll see in 30 minutes if that works!

**Comment by edireson** [comment]
same/similar error. led me to https://www.jessesquires.com/blog/2021/08/23/caching-bundler-on-github-actions/ - so I'm trying that out now, but heading home now
